name: test_notification_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  get_it: ^8.0.3
  logger: ^2.5.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  rxdart: ^0.28.0
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.2.1
  cloud_firestore: ^5.6.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  intl: ^0.20.2
  http: ^1.3.0
  shared_preferences: ^2.4.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.14
  custom_lint: ^0.7.1
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true

  assets:
    - .env